### ISSUE TITLE
Change logger to pino to improve performance

### ISSUE THREAD

**Issue by jesusprubio** [IBMResearch/hume#1]
https://github.com/pinojs/pino#benchmarks
https://www.nearform.com/blog/cost-logging
https://www.nearform.com/blog/sematext-guest-post-pino-fastest-node-js-logger-production/

https://github.com/IBMResearch/hume/blob/master/packages/hume-utils/lib/Logger.js

**Comment by ismaelRozas** [comment]
Reopen the issue to fix how to pass the params to pino log
